apiVersion: v2
name: reports-server
type: application
version: 0.1.24-rc1
appVersion: v0.1.20-rc2
keywords:
- kubernetes
- policy reports storage
- postgresql
sources:
- https://github.com/nirmata/reports-server
maintainers:
- name: Nirmata
  url: https://kyverno.io/
  email: cncf-kyverno-maintainers@lists.cncf.io
kubeVersion: ">=1.16.0-0"
dependencies:
- condition: postgresql.enabled
  name: cloudnative-pg
  version: 0.22.0
  repository: https://cloudnative-pg.github.io/charts
